export const fdmsRoutes = {
  verifyTaxpayerInformation: "/api/v7.2/verifyTaxpayerInformation",
  registerDevice: "/api/v7.2/registerDevice",
  issueCertificate: "/api/v7.2/issueCertificate",
  getConfig: "/api/v7.2/getConfig",
  getStatus: "/api/v7.2/getStatus",
  openDay: "/api/v7.2/openDay",
  submitReceipt: "/api/v7.2/submitReceipt",
  submitFile: "/api/v7.2/submitFile",
  getFileStatus: "/api/v7.2/getFileStatus",
  closeDay: "/api/v7.2/closeDay",
  getServerCertificate: "/api/v7.2/getServerCertificate",
  ping: "/api/v7.2/ping",
  getUsersList: "/api/v7.2/getUsersList",
  login: "/api/v7.2/login",
  createUserBegin: "/api/v7.2/createUserBegin",
  createUserConfirm: "/api/v7.2/createUserConfirm",
  sendSecurityCode: "/api/v7.2/sendSecurityCode",
  sendSecurityCodeContactChange: "/api/v7.2/sendSecurityCodeContactChange",
  confirmUserContactChange: "/api/v7.2/confirmUserContactChange",
} as const;
